javax:
  sql:
    DataSource:
      default:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/dynamiclinkdb
          user: appuser
          password: secret
        maximumPoolSize: 10
        minimumIdle: 2

mongo:
  connection-string: mongodb://mongoadmin:secret@localhost:27017/analyticsdb?authSource=admin
  database: analyticsdb